#!/usr/bin/env bash
FASTQ_STUB="@HWI-ST423:258:C0MLUACXX:5:1101:1235:2219 1:N:0:ATCACG
CTAGGGTTTTTCGAATAACTCTTTCCGGAAGATACNNNGGAAGAANNNTGCAAACCGGACTTTACGGACTTGTGATTTGTATTTCGATAGAGCCAACGCGC
+
CCCFFFDFHHHHHJJJJJJJJIJJJJJJJJJIIJI###08?DHEH###-5@@GIJIHHEDDEEDDDDBDDDDDDCDEEDDEEEEDCDDDDDCCBD?7<>B@
@HWI-ST423:258:C0MLUACXX:5:1101:1176:2228 1:N:0:ATCACG
AAAAGCAGCGTGATTATGAGGAGCGCATGAGTAATNNNGCTTATCNNAGAGCGATGAAAGATATGAAAATTGCTGGTTTAAATCCAATTCTTGCTTATTCA
+
CCCFFFFFHHHHHIJJIJGIJGIGHGGIJIJGGII###07BGHIG##--5CDGEHHFFDEFFEEEEEDCCDDDDDDCCDDDCCCDCDDDDDDCDDDCCDDB
@HWI-ST423:258:C0MLUACXX:5:1101:1467:2070 1:N:0:ATCACG
CNATAGATTTTTCTTTTTCGAATACCTATTCATCANNNGTTCAGNNNNNNTCTGTCTTTCAGAACATTTCCGTTGGTGGCATCGACGTGATAGTAGACATT
+
C#1ADDFFHHHHFIJJJJJJJJJJJJJGIJIJJJJ###10?GH<######0-<FFGHGIIJHIIGIEHCHEHFFEFBDDCDACBDDDBDBDCCADDCDCC>
@HWI-ST423:258:C0MLUACXX:5:1101:1493:2130 1:Y:0:ATCACG
TCCCACATGGAACGAAGAGTAACCTTGAAGAAGTTNNNGCGAGGNNNNNTACGGGTTTGAATAGGGAATGCTATAGGCATAAGCTCGAGCTCGAGTTCGGG
+
--08-6?@<9@##########################################################################################
@HWI-ST423:258:C0MLUACXX:5:1101:1280:2142 1:N:0:ATCACG
TTTTCCGTCCATATTCTATTCCAAGCAACTCCATCNNNTGCCCTNNNNNCCTTCCAAATATGGTTTACTCCGGTGATTACGTATGCGTTTTCTTCTTGCTT
+
CCCFFFFFHHHHHJJJJJJJJIJIJJJJJJJJIIG###1:BGII#####0-<CHHCGHHIIGGIIJGFHHHFD<ACCDEDDBCCDDD<@DDDDDCDC@AD:"

# https://en.wikipedia.org/wiki/FASTQ_format
echo "$FASTQ_STUB" | sed -e 'n;n;n;y/!"#$%&'\''()*+,-.\/0123456789:;<=>?@ABCDEFGHIJKL/▁▁▁▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇██████/'
